### ISSUE TITLE
test: add benchmark tracefiles for regression testing

### ISSUE THREAD

**Issue by jdsika** [lichtblick-suite/asam-osi-converter#7]
## Description

Generate benchmark tracefiles to use for regression testing and performance validation of the converter.

### Tasks

1. Generate benchmark tracefiles using [gt-gen-core](https://gitlab.eclipse.org/eclipse/openpass/gt-gen-simulator) (and/or esmini)
2. Convert to OSI MCAP format using the [OSI MCAP specification](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/833) implemented in [ASAM OSI Utilities](https://github.com/Lichtblick-Suite/asam-osi-utilities)
3. Add the resulting `.mcap` benchmark tracefiles to `example-data/`
4. Verify the converter visualizes them correctly via `local-install`
5. Use them in automated regression tests (compare rendered output across versions)

### Acceptance criteria

- [ ] At least one benchmark tracefile covering: moving objects, lanes, traffic signs, traffic lights
- [ ] Tracefile follows the OSI MCAP specification
- [ ] Converter renders the tracefile without errors or warnings
- [ ] Tests validate no visual regression between releases

**Comment by jdsika** [comment]
The example file has an unsupported topic: /sim/groundtruth_topic

**Comment by jdsika** [comment]
@thomassedlmayer I would recommend to use the following scenarios as benchmark using esmini as simulator:
* [ALSK Scenarios](https://github.com/openMSL/sl-3-1-osc-alks-scenarios)
* [NCAP Scenarios](https://github.com/vectorgrp/OSC-NCAP-scenarios)

**Comment by jdsika** [comment]
We also have a set of example scenarios in [OpenPASS](https://gitlab.eclipse.org/eclipse/openpass/opSimulation/-/tree/main/sim/contrib/examples/Configurations?ref_type=heads)
